name: Scheduled Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 07 * * 1" # Runs every Monday at 09:00 CEST (07:00 UTC)

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build Quarto site
        run: quarto render

      - name: Restore lychee cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --config lychee.toml
            './**/*.md' 
            './**/*.qmd' 
            './**/*.html' 
          fail: true  # Fail the job if any links are broken
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save lychee cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}