name: Scheduled Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * 0" # Runs every Sunday at 20:00 (CEST)

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build Quarto site
        run: quarto render

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --config lychee.toml
            './**/*.md' 
            './**/*.qmd' 
            './**/*.html' 
          fail: true  # Fail the job if any links are broken
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}